name: Deploy to Playground

on:
  push:
    branches:
      - master

env:
  DIRECTORY: /var/www/projects/pandudpn/cart
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_URL: ${{ secrets.DOCKER_USERNAME }}/shopping-cart-api
  SSH_KEY: ${{ secrets.SSH }}

jobs:
  setup-playground-shopping-cart-api:
    name: Setup build, push and deploy into VPS our Playground
    runs-on: ubuntu-20.04

    steps:
      ## checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push image into Registry
        run: |-
          docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }} && \
          docker build -t ${{ env.DOCKER_URL }}:beta . && \
          docker push ${{ env.DOCKER_URL }}

      - name: Deploy into VPS
        run: |-
          echo ${{ env.SSH_KEY }} > .ssh_key && \
          ssh -i .ssh_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          cd ${{ env.DIRECTORY }} && docker-compose pull && docker-compose up -d
