name: Deploy to Playground

on:
  push:
    branches:
      - master

env:
  DIRECTORY: /var/www/projects/pandudpn/cart
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_URL: ${{ secrets.DOCKER_USERNAME }}/shopping-cart
  SSH_KEY: ${{ secrets.SSH }}

jobs:
  build-image:
    name: Build and Push Image
    runs-on: ubuntu-20.04
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
      # build and push image
      - name: Build and Push image into Registry
        run: |-
          docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }} && \
          docker build -t ${{ env.DOCKER_URL }}:dev . && \
          docker push ${{ env.DOCKER_URL }}:dev

  deploy:
    needs: [build-image]
    name: Deploy to Playground
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy into VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            cd ${{ env.DIRECTORY }} && docker-compose pull && docker-compose up -d
